import mongoose, { Schema } from "mongoose";
export const breeds = [
  "Akita",
  "Australian Shepherd",
  "Beagle",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Border Collie",
  "Boxer",
  "Bulldog",
  "Bullmastiff",
  "Cane Corso",
  "Chihuahua",
  "Cocker Spaniel",
  "Dachshund",
  "Dalmatian",
  "Doberman Pinscher",
  "English Bulldog",
  "French Bulldog",
  "German Shepherd",
  "German Shorthaired Pointer",
  "Golden Retriever",
  "Goldendoodle",
  "Great Dane",
  "Greyhound",
  "Husky",
  "Havanese",
  "Labrador Retriever",
  "Maltese",
  "Miniature Schnauzer",
  "Mutt",
  "Newfoundland",
  "Pembroke Welsh Corgi",
  "Pitbull",
  "Pomeranian",
  "Poodle",
  "Pug",
  "Russian Toy",
  "Rottweiler",
  "Saint Bernard",
  "Samoyed",
  "Schnauzer",
  "Shetland Sheepdog",
  "Shih Tzu",
  "Siberian Husky",
  "Staffordshire Bull Terrier",
  "Vizsla",
  "Weimaraner",
  "West Highland White Terrier",
  "Yorkshire Terrier",
];

const DogSchema = new Schema({
  breed: [
    {
      type: String,
      enum: breeds,
    },
  ],
  name: { type: String },
  age: { type: String },
  about: { type: String },
  gender: { type: String },
  image: { type: String },
  likes: [{ type: Schema.Types.ObjectId, ref: "dogs" }],
  user: { type: Schema.Types.ObjectId, ref: "users" },
});

export default mongoose.model("dogs", DogSchema);
